import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// Brand Colors
const COLORS = {
  primary: [44, 95, 45],      // Altuvera Green
  primaryLight: [220, 252, 231],
  secondary: [22, 163, 74],
  accent: [134, 239, 172],
  dark: [20, 83, 45],
  text: [31, 41, 55],
  textLight: [107, 114, 128],
  white: [255, 255, 255],
  background: [249, 250, 251],
};

/**
 * Add professional header to PDF
 */
const addPDFHeader = (pdf, title, subtitle = '') => {
  const pageWidth = pdf.internal.pageSize.getWidth();

  // Background accent bar
  pdf.setFillColor(...COLORS.primary);
  pdf.rect(0, 0, pageWidth, 35, 'F');

  // Logo/Brand
  pdf.setFontSize(28);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(...COLORS.white);
  pdf.text('ALTUVERA', 20, 18);

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(...COLORS.primaryLight);
  pdf.text('East African Safari & Tours', 20, 26);

  // Title section
  if (title) {
    pdf.setFontSize(18);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(...COLORS.primary);
    pdf.text(title, 20, 50);
  }

  if (subtitle) {
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(...COLORS.textLight);
    pdf.text(subtitle, 20, 58);
  }

  return 65; // Return starting Y position for content
};

/**
 * Add professional footer to PDF
 */
const addPDFFooter = (pdf, pageNumber = 1, totalPages = 1) => {
  const pageHeight = pdf.internal.pageSize.getHeight();
  const pageWidth = pdf.internal.pageSize.getWidth();

  // Footer line
  pdf.setDrawColor(...COLORS.primary);
  pdf.setLineWidth(0.5);
  pdf.line(20, pageHeight - 20, pageWidth - 20, pageHeight - 20);

  // Footer text
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(...COLORS.textLight);
  
  const leftText = `Generated by Altuvera | ${new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  })}`;
  
  const rightText = `Page ${pageNumber} of ${totalPages}`;
  
  pdf.text(leftText, 20, pageHeight - 12);
  pdf.text(rightText, pageWidth - 20, pageHeight - 12, { align: 'right' });

  // Website
  pdf.setTextColor(...COLORS.secondary);
  pdf.text('www.altuvera.com', pageWidth / 2, pageHeight - 12, { align: 'center' });
};

/**
 * Generate Professional Package Checklist PDF
 */
export const generatePackageChecklist = (tourData = {}, expenses = {}, userInfo = {}) => {
  const {
    tourName = 'African Safari Adventure',
    destination = 'East Africa',
    duration = '7 Days',
    startDate = new Date().toLocaleDateString(),
    endDate = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toLocaleDateString(),
  } = tourData;

  const {
    accommodation = 0,
    transport = 0,
    meals = 0,
    activities = 0,
    miscellaneous = 0,
  } = expenses;

  const { name = 'Traveler', email = '', phone = '' } = userInfo;

  const pdf = new jsPDF('p', 'mm', 'a4');
  let currentPage = 1;

  // Header
  let yPos = addPDFHeader(pdf, 'Travel Package Checklist', tourName);

  // Traveler Info Card
  pdf.setFillColor(...COLORS.primaryLight);
  pdf.roundedRect(20, yPos, 170, 30, 3, 3, 'F');
  
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(...COLORS.primary);
  pdf.text('Traveler Information', 25, yPos + 8);

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(...COLORS.text);
  pdf.text(`Name: ${name}`, 25, yPos + 16);
  pdf.text(`Email: ${email}`, 25, yPos + 22);
  pdf.text(`Phone: ${phone}`, 100, yPos + 22);

  yPos += 40;

  // Tour Details Section
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(...COLORS.primary);
  pdf.text('Tour Details', 20, yPos);
  yPos += 8;

  autoTable(pdf, {
    startY: yPos,
    head: [['Detail', 'Information']],
    body: [
      ['Tour Package', tourName],
      ['Destination', destination],
      ['Duration', duration],
      ['Departure Date', startDate],
      ['Return Date', endDate],
    ],
    headStyles: {
      fillColor: COLORS.primary,
      textColor: COLORS.white,
      fontStyle: 'bold',
      fontSize: 11,
    },
    bodyStyles: {
      textColor: COLORS.text,
      fontSize: 10,
    },
    alternateRowStyles: {
      fillColor: COLORS.primaryLight,
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 50 },
      1: { cellWidth: 'auto' },
    },
    margin: { left: 20, right: 20 },
    theme: 'grid',
  });

  yPos = pdf.lastAutoTable.finalY + 15;

  // Expenses Section
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(...COLORS.primary);
  pdf.text('Package Investment Breakdown', 20, yPos);
  yPos += 8;

  const total = accommodation + transport + meals + activities + miscellaneous;

  autoTable(pdf, {
    startY: yPos,
    head: [['Expense Category', 'Amount (USD)']],
    body: [
      ['🏨 Accommodation', `$${accommodation.toLocaleString('en-US', { minimumFractionDigits: 2 })}`],
      ['🚗 Transport & Transfers', `$${transport.toLocaleString('en-US', { minimumFractionDigits: 2 })}`],
      ['🍽️ Meals & Dining', `$${meals.toLocaleString('en-US', { minimumFractionDigits: 2 })}`],
      ['🎯 Activities & Guides', `$${activities.toLocaleString('en-US', { minimumFractionDigits: 2 })}`],
      ['📋 Miscellaneous', `$${miscellaneous.toLocaleString('en-US', { minimumFractionDigits: 2 })}`],
    ],
    foot: [['TOTAL INVESTMENT', `$${total.toLocaleString('en-US', { minimumFractionDigits: 2 })}`]],
    headStyles: {
      fillColor: COLORS.primary,
      textColor: COLORS.white,
      fontStyle: 'bold',
      fontSize: 11,
    },
    footStyles: {
      fillColor: COLORS.secondary,
      textColor: COLORS.white,
      fontStyle: 'bold',
      fontSize: 12,
    },
    bodyStyles: {
      textColor: COLORS.text,
      fontSize: 10,
    },
    alternateRowStyles: {
      fillColor: COLORS.primaryLight,
    },
    columnStyles: {
      0: { cellWidth: 100 },
      1: { halign: 'right', fontStyle: 'bold' },
    },
    margin: { left: 20, right: 20 },
    theme: 'grid',
  });

  // New page for packing checklist
  pdf.addPage();
  currentPage++;
  yPos = addPDFHeader(pdf, 'Essential Packing Checklist', 'Curated for your East African adventure');

  const packingCategories = [
    {
      category: '📄 Essential Documents',
      icon: '📄',
      items: ['Valid Passport (6+ months validity)', 'Travel Insurance Certificate', 'Booking Confirmation', 'Visa/Entry Permits', 'Driver\'s License', 'Emergency Contacts List', 'Vaccination Certificate (Yellow Fever)']
    },
    {
      category: '👕 Clothing Essentials',
      icon: '👕',
      items: ['Lightweight long-sleeve shirts (3-4)', 'Convertible pants/shorts (2-3)', 'Comfortable hiking boots', 'Sandals/casual shoes', 'Fleece jacket/sweater', 'Waterproof rain jacket', 'Wide-brim hat/cap', 'Moisture-wicking socks (5-7 pairs)', 'Swimwear']
    },
    {
      category: '🧴 Health & Toiletries',
      icon: '🧴',
      items: ['Sunscreen SPF 50+', 'Insect repellent (DEET 30%)', 'Personal medications', 'Antimalarial prophylaxis', 'First aid kit', 'Hand sanitizer', 'Toiletries kit', 'Wet wipes', 'Lip balm with SPF']
    },
    {
      category: '📷 Photography & Electronics',
      icon: '📷',
      items: ['Camera with telephoto lens', 'Binoculars (8x42 or 10x42)', 'Smartphone & charger', 'Universal power adapter', 'Portable power bank', 'Extra memory cards', 'Camera cleaning kit', 'Waterproof bags for electronics']
    },
    {
      category: '🎒 Adventure Gear',
      icon: '🎒',
      items: ['Daypack/backpack', 'Reusable water bottle', 'Headlamp/flashlight', 'Sunglasses (UV protection)', 'Travel pillow', 'Quick-dry towel', 'Ziplock bags', 'Notebook & pen']
    }
  ];

  packingCategories.forEach((section, index) => {
    if (yPos > 240) {
      pdf.addPage();
      currentPage++;
      yPos = 40;
    }

    // Category header with icon
    pdf.setFillColor(...COLORS.primary);
    pdf.roundedRect(20, yPos - 5, 170, 12, 2, 2, 'F');
    
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(...COLORS.white);
    pdf.text(section.category, 25, yPos + 3);
    
    yPos += 15;

    // Items with checkboxes
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(...COLORS.text);

    section.items.forEach((item) => {
      if (yPos > 270) {
        pdf.addPage();
        currentPage++;
        yPos = 40;
      }

      // Checkbox
      pdf.setDrawColor(...COLORS.primary);
      pdf.setLineWidth(0.3);
      pdf.rect(25, yPos - 3, 4, 4);

      // Item text
      const wrappedText = pdf.splitTextToSize(item, 135);
      pdf.text(wrappedText, 32, yPos);
      yPos += (wrappedText.length * 5) + 2;
    });

    yPos += 8;
  });

  // Add footers to all pages
  const totalPages = pdf.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    addPDFFooter(pdf, i, totalPages);
  }

  return pdf;
};

/**
 * Generate Travel Tips & Guide PDF
 */
export const generateTravelGuide = (tips = [], tourName = 'East Africa Safari') => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  let currentPage = 1;

  let yPos = addPDFHeader(pdf, 'Travel Tips & Essential Guide', `Expert advice for ${tourName}`);

  const defaultTips = [
    {
      title: '🌍 Best Time to Visit',
      content: 'The dry season (June-October and January-February) offers optimal wildlife viewing as animals congregate around water sources. The Great Migration occurs July-October in the Serengeti.',
      priority: 'high'
    },
    {
      title: '🎒 Packing Smart',
      content: 'Neutral colors (khaki, olive, beige) are essential - bright colors can disturb wildlife. Layer clothing for temperature changes between morning game drives (cool) and midday (hot).',
      priority: 'high'
    },
    {
      title: '💉 Health Precautions',
      content: 'Consult your doctor 6-8 weeks before travel. Required: Yellow Fever vaccination. Recommended: Typhoid, Hepatitis A&B, Tetanus. Antimalarial medication is essential for most regions.',
      priority: 'critical'
    },
    {
      title: '📸 Photography Mastery',
      content: 'Golden hours (6-9 AM, 4-7 PM) provide the best lighting. Bring minimum 200mm lens for wildlife. Dust protection is crucial. Always ask permission before photographing local people.',
      priority: 'medium'
    },
    {
      title: '🦁 Wildlife Etiquette',
      content: 'Maintain 25+ meters from wildlife. Never exit vehicles unless permitted. No feeding animals. Silence and patience yield the best sightings. Follow your guide\'s instructions absolutely.',
      priority: 'critical'
    },
    {
      title: '💰 Money Matters',
      content: 'US Dollars (post-2013 bills) are widely accepted. Carry small denominations for tips. Credit cards work in major hotels but cash is king in rural areas. ATMs available in major cities.',
      priority: 'medium'
    },
    {
      title: '🌐 Connectivity',
      content: 'Purchase local SIM cards at airports for affordable data. Safari lodges often have limited WiFi. Download offline maps before departing. Consider portable WiFi devices for consistent connection.',
      priority: 'low'
    },
    {
      title: '🍽️ Culinary Experience',
      content: 'Try local dishes like Ugali, Nyama Choma, and Pilau. Bottled water only. Avoid raw vegetables and unpeeled fruits. Food in lodges is generally safe and delicious.',
      priority: 'medium'
    }
  ];

  const tipsToRender = tips.length > 0 ? tips : defaultTips;

  tipsToRender.forEach((tip, index) => {
    if (yPos > 240) {
      pdf.addPage();
      currentPage++;
      yPos = 40;
    }

    const tipData = typeof tip === 'string' ? { title: `Tip ${index + 1}`, content: tip, priority: 'medium' } : tip;

    // Priority badge
    const priorityColors = {
      critical: [220, 38, 38],
      high: [234, 88, 12],
      medium: [22, 163, 74],
      low: [107, 114, 128]
    };

    const priorityColor = priorityColors[tipData.priority] || priorityColors.medium;

    // Tip container
    pdf.setFillColor(249, 250, 251);
    pdf.roundedRect(20, yPos - 5, 170, 'auto', 3, 3, 'F');

    // Priority indicator
    if (tipData.priority) {
      pdf.setFillColor(...priorityColor);
      pdf.circle(25, yPos + 2, 2, 'F');
    }

    // Title
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(...COLORS.primary);
    pdf.text(tipData.title, 30, yPos + 3);

    yPos += 10;

    // Content
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(...COLORS.text);
    const wrappedContent = pdf.splitTextToSize(tipData.content, 160);
    
    wrappedContent.forEach((line) => {
      if (yPos > 270) {
        pdf.addPage();
        currentPage++;
        yPos = 40;
      }
      pdf.text(line, 25, yPos);
      yPos += 5;
    });

    yPos += 10;
  });

  // Add footers
  const totalPages = pdf.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    addPDFFooter(pdf, i, totalPages);
  }

  return pdf;
};

/**
 * Generate Booking Confirmation PDF
 */
export const generateBookingConfirmation = (bookingData = {}) => {
  const {
    bookingId = 'ALT-' + Date.now(),
    tourName = 'Safari Adventure',
    travelerName = 'Guest',
    email = '',
    phone = '',
    startDate = new Date().toLocaleDateString(),
    endDate = '',
    guests = 1,
    totalAmount = 0,
    depositPaid = 0,
    balanceDue = 0,
    paymentStatus = 'Confirmed',
  } = bookingData;

  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();

  let yPos = addPDFHeader(pdf, 'Booking Confirmation', `Your adventure awaits!`);

  // Confirmation badge
  pdf.setFillColor(...COLORS.secondary);
  pdf.roundedRect(pageWidth - 70, 15, 50, 15, 3, 3, 'F');
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(...COLORS.white);
  pdf.text('✓ CONFIRMED', pageWidth - 45, 24, { align: 'center' });

  // Booking Reference
  pdf.setFillColor(...COLORS.primaryLight);
  pdf.roundedRect(20, yPos, 170, 15, 2, 2, 'F');
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(...COLORS.primary);
  pdf.text(`Booking Reference: ${bookingId}`, pageWidth / 2, yPos + 10, { align: 'center' });

  yPos += 25;

  // Booking Details
  autoTable(pdf, {
    startY: yPos,
    head: [['Booking Information', '']],
    body: [
      ['Tour Package', tourName],
      ['Lead Traveler', travelerName],
      ['Email Address', email],
      ['Phone Number', phone],
      ['Departure Date', startDate],
      ['Return Date', endDate || 'To be confirmed'],
      ['Number of Guests', `${guests} ${guests === 1 ? 'Person' : 'People'}`],
    ],
    headStyles: {
      fillColor: COLORS.primary,
      textColor: COLORS.white,
      fontSize: 12,
      fontStyle: 'bold',
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 70, fillColor: COLORS.primaryLight },
      1: { cellWidth: 'auto' },
    },
    bodyStyles: {
      textColor: COLORS.text,
      fontSize: 10,
    },
    margin: { left: 20, right: 20 },
    theme: 'grid',
  });

  yPos = pdf.lastAutoTable.finalY + 15;

  // Payment Summary
  autoTable(pdf, {
    startY: yPos,
    head: [['Payment Summary', 'Amount (USD)']],
    body: [
      ['Package Total', `$${totalAmount.toLocaleString('en-US', { minimumFractionDigits: 2 })}`],
      ['Deposit Paid', `$${depositPaid.toLocaleString('en-US', { minimumFractionDigits: 2 })}`],
      ['Balance Due', `$${balanceDue.toLocaleString('en-US', { minimumFractionDigits: 2 })}`],
    ],
    foot: [['Payment Status', paymentStatus.toUpperCase()]],
    headStyles: {
      fillColor: COLORS.primary,
      textColor: COLORS.white,
      fontSize: 12,
      fontStyle: 'bold',
    },
    footStyles: {
      fillColor: balanceDue > 0 ? [234, 179, 8] : COLORS.secondary,
      textColor: COLORS.white,
      fontSize: 11,
      fontStyle: 'bold',
    },
    bodyStyles: {
      textColor: COLORS.text,
      fontSize: 10,
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 70 },
      1: { halign: 'right', fontStyle: 'bold' },
    },
    margin: { left: 20, right: 20 },
    theme: 'grid',
  });

  yPos = pdf.lastAutoTable.finalY + 20;

  // Important Information
  pdf.setFillColor(...COLORS.primaryLight);
  pdf.roundedRect(20, yPos, 170, 55, 3, 3, 'F');

  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(...COLORS.primary);
  pdf.text('📋 Important Information', 25, yPos + 8);

  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(...COLORS.text);

  const importantNotes = [
    '✓ Please present this confirmation and valid photo ID at departure',
    '✓ Final payment due 30 days prior to departure date',
    '✓ Standard cancellation policy applies (see Terms & Conditions)',
    '✓ Travel insurance is highly recommended',
    '✓ Contact us at altuverasafari@gmail.com or +254-XXX-XXXX for assistance'
  ];

  let noteY = yPos + 16;
  importantNotes.forEach(note => {
    pdf.text(note, 25, noteY);
    noteY += 6;
  });

  addPDFFooter(pdf, 1, 1);

  return pdf;
};

/**
 * Download PDF with enhanced error handling
 */
export const downloadPDF = (pdf, filename = 'document.pdf') => {
  try {
    if (!pdf) throw new Error('No PDF document provided');
    pdf.save(filename);
    return { success: true, message: 'PDF downloaded successfully' };
  } catch (error) {
    console.error('PDF Download Error:', error);
    return { success: false, message: error.message };
  }
};

/**
 * Preview PDF in new tab
 */
export const previewPDF = (pdf) => {
  try {
    if (!pdf) throw new Error('No PDF document provided');
    const blob = pdf.output('blob');
    const url = URL.createObjectURL(blob);
    window.open(url, '_blank');
    return { success: true, message: 'PDF opened in new tab' };
  } catch (error) {
    console.error('PDF Preview Error:', error);
    return { success: false, message: error.message };
  }
};